---
name: Linting and Formatting
on: # yamllint disable-line rule:truthy
  pull_request: {}
  workflow_dispatch: {}
jobs:
  shell:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-code-quality-shell.yaml@v1.1.0
    with:
      osl-utils-tag: v1.1.0
  python:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-code-quality-python.yaml@v1.1.0
    with:
      osl-utils-tag: v1.1.0
  jinja2:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-code-quality-jinja2.yaml@v1.1.0
    with:
      osl-utils-tag: v1.1.0
  # These yaml lints aren't working
  # yaml:
  #   uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-code-quality-yaml.yaml@v1.1.0
  #   with:
  #     osl-utils-tag: v1.1.0
  dockerfile:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-code-quality-dockerfile.yaml@v1.1.0
    with:
      osl-utils-tag: v1.1.0
  markdown:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-code-quality-markdown.yaml@v1.1.0
    with:
      # The osl-utils docker tag. Should match the above tag in prod.
      # Other potential values: `prod`, `test`, `dev`, <dev-initials>, <commit-hash>
      osl-utils-tag: v1.1.0
