---
name: PR - Run Code Coverage Analysis
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, review_requested]
    branches:
      - main
  workflow_dispatch: {}

jobs:

  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v1.0.2
    with:
      tagname: ${{ inputs.tagname || github.ref_name }}

  generate-coverage:
    runs-on: ubuntu-latest
    needs:
      - setup
    environment: ${{ needs.setup.outputs.environment }}
    container: ghcr.io/asfopensarlab/osl-utils:v1.0.3
    env:
      DEPLOY_PREFIX: ${{ needs.setup.outputs.deploy_prefix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Make Coverage File
        run: |
          make test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: /tmp/coverage.xml
          retention-days: 10

  coverage:
    needs:
      - generate-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: /tmp/

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: /tmp/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
